{% set name = "maxsmi" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/volkamerlab/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: 98db389dba11e1cf88220cb833aa1b0c6bb3bc4054775d2a7ab4c9843c71b9cc

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - jupyter
    - jupyterlab
    - rdkit >=2018.09.2.0
    - scikit-learn
    - requests
    - tqdm
    - pytorch
    - matplotlib-base
    - selfies
    - deepsmiles
    - dataframe_image

test:
  imports:
    - maxsmi

about:
  home: https://github.com/volkamerlab/maxsmi
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Maximizing molecular property prediction performance using SMILES augmentation and deep learning
  description: |
    SMILES augmentation for deep learning based molecular property and activity prediction.
  doc_url: https://maxsmi.readthedocs.io/en/latest/
  dev_url: https://github.com/volkamerlab/maxsmi

extra:
  recipe-maintainers:
    - t-kimber
